FROM node:14-alpine

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste des fichiers de l'application
COPY . .

# Exposer le port d'écoute
EXPOSE 8081

# Démarrer l'application
CMD ["npm", "start"]
